# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3eb1879858738cea2f0475f0dc89ebd7"
application_url = "https://shopify-hideprice.onrender.com/"
embedded = true
name = "hide-price"
handle = "hide-price-12"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopify-hideprice.onrender.com/api/auth" ]

[pos]
embedded = false
